language: c
script:
  # Babyc works best on 32-bit kernels, so check what we're running.
  - "uname -a"
  # We deliberately separate building babyc from building the tests,
  # to make it clearer where warnings are coming from.
  - "make"
  - "make test"

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "N4GqP/jW/OUVtNFzUuXmPUPkoF4lxtYuezvwP+GDkJT/8FmEL0e7TA7j+Va3tEvhFaVxg8wMHMmvCibXqDTBqDTfMRV0Vz8uZpr/RD0Q46Svv3ErHxzFfMjGIjVBVTCpIEIxFU0awlocgM7bGBjSYViOJUezWfGUfMqCueZ5lcI="

addons:
  coverity_scan:
    project:
      name: "Wilfred/babyc"
      description: "Build submitted via Travis CI"
    notification_email: me@wilfred.me.uk
    build_command: "make -j 4"
    # todo: move to a coverity_scan branch once configured and working
    branch_pattern: master
